name: Full CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # ====================================================
  # GIAI ĐOẠN 1: CI (TÍCH HỢP - KIỂM TRA)
  # Diễn ra hoàn toàn trên máy ảo của GitHub
  # ====================================================
  kiem_tra_chat_luong:
    #Đây chính là câu lệnh báo rằng sử dụng máy của Github
    runs-on: ubuntu-latest

    steps:
      - name: 1. Lấy code về máy GitHub
        uses: actions/checkout@v2

      - name: 2. Cài môi trường Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 3. Cài thư viện (Test package.json)
        run: npm install

      - name: 4. Build thử (Test cú pháp code)
        # Nếu bước này lỗi -> Dừng ngay lập tức -> Server AWS an toàn
        run: npm run build

  # ====================================================
  # GIAI ĐOẠN 2: CD (TRIỂN KHAI - GIAO HÀNG)
  # Chỉ chạy khi giai đoạn 1 thành công
  # ====================================================
  giao_hang_aws:
    needs: kiem_tra_chat_luong # <--- CHỐT CHẶN AN TOÀN

    #Đây chính là câu lệnh báo rằng sử dụng máy của Github
    runs-on: ubuntu-latest

    steps:
      - name: Kết nối SSH và Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: 22

          # Các lệnh này sẽ được gửi sang máy AWS để chạy
          script: |
            # Lưu ý: Sửa đường dẫn Project_FER nếu máy bạn khác
            cd /home/ubuntu/Project_FER
            git pull origin main
            npm install

            # Restart Backend
            sudo systemctl restart music-wave-api

            # Build Frontend (Chấp nhận build lại ở server)
            npm run build
            sudo rm -rf /var/www/html/*
            sudo cp -r build/* /var/www/html/
